server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bankmanager
  datasource:
    url: jdbc:mysql://localhost:3306/bank_manager
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

